In [12]:
import pandas as pd

In [13]:
df_bibliotecas = pd.read_csv("bibliotecas.csv")
df_afluencia = pd.read_csv("afluencia.csv")
df_prestamos = pd.read_csv("prestamos.csv")

In [23]:
df_afluencia

,fecha,hora,id_biblioteca,visitantes,capacidad_registrada,fuente_registro
0,2026-09-01,9,B02,108,220,Conteo de acceso
1,2026-09-01,9,B03,59,185,Conteo de acceso
2,2026-09-01,9,B05,61,130,Conteo de acceso
3,2026-09-01,9,B06,128,210,Conteo de acceso
4,2026-09-01,9,B07,44,125,Conteo de acceso
...,...,...,...,...,...,...
431,2026-09-14,18,B04,129,155,Conteo de acceso
432,2026-09-14,18,B06,124,210,Conteo de acceso
433,2026-09-14,18,B07,71,125,Conteo de acceso
434,2026-09-14,18,B09,133,170,Conteo de acceso
435,2026-09-14,18,B11,135,190,Conteo de acceso

Cada fila es la cantidad de visitandes con la capicidad registrada segun un dia, una hora y una biblioteca en especifico, la llave propuesta es la union de estas tres variables.

In [4]:
df_prestamos

,id_prestamo,fecha,hora,id_biblioteca,id_usuario,tipo_material,categoria,modalidad_prestamo,dias_prestamo
0,P0103,2026-09-14,12,B01,U0159,Revista,Infantil,Sala,17
1,P0186,2026-09-06,9,B01,U0115,Revista,Tecnología,Domicilio,2
2,P0194,2026-09-08,15,B07,U0021,Libro,Ciencias,Domicilio,15
3,P0224,2026-09-07,15,B12,U0036,Revista,Literatura,Domicilio,12
4,P0074,2026-09-04,12,B05,U0058,Revista,Arte,Sala,19
...,...,...,...,...,...,...,...,...,...
235,P0145,2026-09-02,12,B11,U0147,Libro,Infantil,Domicilio,19
236,P0073,2026-09-03,18,B11,U0150,Libro,Literatura,Sala,20
237,P0002,2026-09-07,15,B07,U0016,Libro,Literatura,Sala,18
238,P0094,2026-09-04,15,B09,U0109,Libro,Infantil,Domicilio,13
239,P0125,2026-09-06,12,B12,U0004,Revista,Arte,Domicilio,19

cada fila representa un prestamo de un recurso de la biblioteca, la llave propuesta es el "id_prestamo"

In [5]:
df_bibliotecas

,id_biblioteca,nombre_biblioteca,localidad,capacidad_personas,puestos_lectura,estado
0,B01,Biblioteca Bosque de Letras,Chapinero,145,87,Activa
1,B02,Biblioteca Altos del Norte,Suba,220,132,Activa
2,B03,Biblioteca Senderos,Kennedy,185,111,Activa
3,B04,Biblioteca Horizonte,Usaquén,155,93,Activa
4,B05,Biblioteca El Encuentro,Bosa,130,78,Activa
5,B06,Biblioteca Las Acacias,Engativá,210,126,Activa
6,B07,Biblioteca Casa del Saber,Teusaquillo,125,75,Activa
7,B08,Biblioteca La Estación Cultural,Barrios Unidos,140,84,Activa
8,B09,Biblioteca Mirador,San Cristóbal,170,102,Activa
9,B10,Biblioteca Puertas Abiertas,Fontibón,150,90,Activa
10,B11,Biblioteca Semillas,Ciudad Bolívar,190,114,Activa
11,B12,Biblioteca Entre Páginas,Puente Aranda,120,72,Activa
12,B13,Biblioteca Piloto Sur,Antonio Nariño,85,51,Piloto

Cada fila representa una biblioteca, siendo su llave el Id_biblioteca

In [6]:
df_afluencia.shape

(436, 6)

In [7]:
df_bibliotecas.shape

(13, 6)

In [8]:
df_prestamos.shape

(240, 9)

In [9]:
df_bibliotecas["id_biblioteca"].duplicated().sum()

np.int64(0)

In [10]:
df_prestamos["id_prestamo"].duplicated().sum()

np.int64(0)

In [17]:
df_afluencia.dtypes

fecha                     str
hora                    int64
id_biblioteca             str
visitantes              int64
capacidad_registrada    int64
fuente_registro           str
dtype: object

In [15]:
df_afluencia["id_afluencias"] = df_afluencia["fecha"] + "_" + df_afluencia["hora"].astype(str) + "_" + df_afluencia["id_biblioteca"]
df_afluencia

,fecha,hora,id_biblioteca,visitantes,capacidad_registrada,fuente_registro,id_afluencias
0,2026-09-01,9,B02,108,220,Conteo de acceso,2026-09-01_9_B02
1,2026-09-01,9,B03,59,185,Conteo de acceso,2026-09-01_9_B03
2,2026-09-01,9,B05,61,130,Conteo de acceso,2026-09-01_9_B05
3,2026-09-01,9,B06,128,210,Conteo de acceso,2026-09-01_9_B06
4,2026-09-01,9,B07,44,125,Conteo de acceso,2026-09-01_9_B07
...,...,...,...,...,...,...,...
431,2026-09-14,18,B04,129,155,Conteo de acceso,2026-09-14_18_B04
432,2026-09-14,18,B06,124,210,Conteo de acceso,2026-09-14_18_B06
433,2026-09-14,18,B07,71,125,Conteo de acceso,2026-09-14_18_B07
434,2026-09-14,18,B09,133,170,Conteo de acceso,2026-09-14_18_B09
435,2026-09-14,18,B11,135,190,Conteo de acceso,2026-09-14_18_B11

In [16]:
df_afluencia["id_afluencias"].duplicated().sum()

np.int64(0)

Las llaves propuestas en bibilioteca y afluencias no presentan ningun duplicado, esto es importante para que el merge no de error, porque si existe alguna llave duplicada merge simplemente multiplica y no muestra el error dandonos como resultado una tabla inservible.

In [60]:
df_prestamos["id_afluencias"] = df_prestamos["fecha"] + "_" + df_prestamos["hora"].astype(str) + "_" + df_prestamos["id_biblioteca"]
df_prestamos

,id_prestamo,fecha,hora,id_biblioteca,id_usuario,tipo_material,categoria,modalidad_prestamo,dias_prestamo,id_afluencias
0,P0103,2026-09-14,12,B01,U0159,Revista,Infantil,Sala,17,2026-09-14_12_B01
1,P0186,2026-09-06,9,B01,U0115,Revista,Tecnología,Domicilio,2,2026-09-06_9_B01
2,P0194,2026-09-08,15,B07,U0021,Libro,Ciencias,Domicilio,15,2026-09-08_15_B07
3,P0224,2026-09-07,15,B12,U0036,Revista,Literatura,Domicilio,12,2026-09-07_15_B12
4,P0074,2026-09-04,12,B05,U0058,Revista,Arte,Sala,19,2026-09-04_12_B05
...,...,...,...,...,...,...,...,...,...,...
235,P0145,2026-09-02,12,B11,U0147,Libro,Infantil,Domicilio,19,2026-09-02_12_B11
236,P0073,2026-09-03,18,B11,U0150,Libro,Literatura,Sala,20,2026-09-03_18_B11
237,P0002,2026-09-07,15,B07,U0016,Libro,Literatura,Sala,18,2026-09-07_15_B07
238,P0094,2026-09-04,15,B09,U0109,Libro,Infantil,Domicilio,13,2026-09-04_15_B09
239,P0125,2026-09-06,12,B12,U0004,Revista,Arte,Domicilio,19,2026-09-06_12_B12

In [61]:

merge_PB_left = df_prestamos.merge(df_bibliotecas, on= "id_biblioteca", how="left")
merge_PB_inner = df_prestamos.merge(df_bibliotecas, on= "id_biblioteca", how="inner")
merge_PB_outer = df_prestamos.merge(df_bibliotecas, on= "id_biblioteca", how="outer")
merge_PB_left

,id_prestamo,fecha,hora,id_biblioteca,id_usuario,tipo_material,categoria,modalidad_prestamo,dias_prestamo,id_afluencias,nombre_biblioteca,localidad,capacidad_personas,puestos_lectura,estado
0,P0103,2026-09-14,12,B01,U0159,Revista,Infantil,Sala,17,2026-09-14_12_B01,Biblioteca Bosque de Letras,Chapinero,145.0,87.0,Activa
1,P0186,2026-09-06,9,B01,U0115,Revista,Tecnología,Domicilio,2,2026-09-06_9_B01,Biblioteca Bosque de Letras,Chapinero,145.0,87.0,Activa
2,P0194,2026-09-08,15,B07,U0021,Libro,Ciencias,Domicilio,15,2026-09-08_15_B07,Biblioteca Casa del Saber,Teusaquillo,125.0,75.0,Activa
3,P0224,2026-09-07,15,B12,U0036,Revista,Literatura,Domicilio,12,2026-09-07_15_B12,Biblioteca Entre Páginas,Puente Aranda,120.0,72.0,Activa
4,P0074,2026-09-04,12,B05,U0058,Revista,Arte,Sala,19,2026-09-04_12_B05,Biblioteca El Encuentro,Bosa,130.0,78.0,Activa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,P0145,2026-09-02,12,B11,U0147,Libro,Infantil,Domicilio,19,2026-09-02_12_B11,Biblioteca Semillas,Ciudad Bolívar,190.0,114.0,Activa
236,P0073,2026-09-03,18,B11,U0150,Libro,Literatura,Sala,20,2026-09-03_18_B11,Biblioteca Semillas,Ciudad Bolívar,190.0,114.0,Activa
237,P0002,2026-09-07,15,B07,U0016,Libro,Literatura,Sala,18,2026-09-07_15_B07,Biblioteca Casa del Saber,Teusaquillo,125.0,75.0,Activa
238,P0094,2026-09-04,15,B09,U0109,Libro,Infantil,Domicilio,13,2026-09-04_15_B09,Biblioteca Mirador,San Cristóbal,170.0,102.0,Activa
239,P0125,2026-09-06,12,B12,U0004,Revista,Arte,Domicilio,19,2026-09-06_12_B12,Biblioteca Entre Páginas,Puente Aranda,120.0,72.0,Activa

In [62]:
merge_PB_left["id_prestamo"].duplicated().sum()

np.int64(0)

cada id_prestamo aparece una sola vez

In [63]:
merge_PB_inner

,id_prestamo,fecha,hora,id_biblioteca,id_usuario,tipo_material,categoria,modalidad_prestamo,dias_prestamo,id_afluencias,nombre_biblioteca,localidad,capacidad_personas,puestos_lectura,estado
0,P0103,2026-09-14,12,B01,U0159,Revista,Infantil,Sala,17,2026-09-14_12_B01,Biblioteca Bosque de Letras,Chapinero,145,87,Activa
1,P0186,2026-09-06,9,B01,U0115,Revista,Tecnología,Domicilio,2,2026-09-06_9_B01,Biblioteca Bosque de Letras,Chapinero,145,87,Activa
2,P0194,2026-09-08,15,B07,U0021,Libro,Ciencias,Domicilio,15,2026-09-08_15_B07,Biblioteca Casa del Saber,Teusaquillo,125,75,Activa
3,P0224,2026-09-07,15,B12,U0036,Revista,Literatura,Domicilio,12,2026-09-07_15_B12,Biblioteca Entre Páginas,Puente Aranda,120,72,Activa
4,P0074,2026-09-04,12,B05,U0058,Revista,Arte,Sala,19,2026-09-04_12_B05,Biblioteca El Encuentro,Bosa,130,78,Activa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,P0145,2026-09-02,12,B11,U0147,Libro,Infantil,Domicilio,19,2026-09-02_12_B11,Biblioteca Semillas,Ciudad Bolívar,190,114,Activa
228,P0073,2026-09-03,18,B11,U0150,Libro,Literatura,Sala,20,2026-09-03_18_B11,Biblioteca Semillas,Ciudad Bolívar,190,114,Activa
229,P0002,2026-09-07,15,B07,U0016,Libro,Literatura,Sala,18,2026-09-07_15_B07,Biblioteca Casa del Saber,Teusaquillo,125,75,Activa
230,P0094,2026-09-04,15,B09,U0109,Libro,Infantil,Domicilio,13,2026-09-04_15_B09,Biblioteca Mirador,San Cristóbal,170,102,Activa
231,P0125,2026-09-06,12,B12,U0004,Revista,Arte,Domicilio,19,2026-09-06_12_B12,Biblioteca Entre Páginas,Puente Aranda,120,72,Activa

In [64]:
merge_PB_outer

,id_prestamo,fecha,hora,id_biblioteca,id_usuario,tipo_material,categoria,modalidad_prestamo,dias_prestamo,id_afluencias,nombre_biblioteca,localidad,capacidad_personas,puestos_lectura,estado
0,P0103,2026-09-14,12.0,B01,U0159,Revista,Infantil,Sala,17.0,2026-09-14_12_B01,Biblioteca Bosque de Letras,Chapinero,145.0,87.0,Activa
1,P0186,2026-09-06,9.0,B01,U0115,Revista,Tecnología,Domicilio,2.0,2026-09-06_9_B01,Biblioteca Bosque de Letras,Chapinero,145.0,87.0,Activa
2,P0099,2026-09-05,12.0,B01,U0154,Revista,Arte,Domicilio,16.0,2026-09-05_12_B01,Biblioteca Bosque de Letras,Chapinero,145.0,87.0,Activa
3,P0110,2026-09-07,15.0,B01,U0093,Libro,Tecnología,Domicilio,5.0,2026-09-07_15_B01,Biblioteca Bosque de Letras,Chapinero,145.0,87.0,Activa
4,P0132,2026-09-02,18.0,B01,U0023,Libro,Arte,Domicilio,16.0,2026-09-02_18_B01,Biblioteca Bosque de Letras,Chapinero,145.0,87.0,Activa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,P0240,2026-09-05,18.0,B99,U0057,Libro,Infantil,Sala,21.0,2026-09-05_18_B99,NaN,NaN,NaN,NaN,NaN
237,P0239,2026-09-05,9.0,B99,U0039,Revista,Ciencias,Sala,9.0,2026-09-05_9_B99,NaN,NaN,NaN,NaN,NaN
238,P0233,2026-09-05,18.0,B99,U0040,Libro,Ciencias,Domicilio,2.0,2026-09-05_18_B99,NaN,NaN,NaN,NaN,NaN
239,P0236,2026-09-10,18.0,B99,U0026,Libro,Tecnología,Domicilio,19.0,2026-09-10_18_B99,NaN,NaN,NaN,NaN,NaN
240,P0234,2026-09-14,15.0,B99,U0036,Libro,Historia,Domicilio,16.0,2026-09-14_15_B99,NaN,NaN,NaN,NaN,NaN

In [65]:
merge_PA_idafluencia = df_prestamos.merge(df_afluencia, on= "id_afluencias", how = "left")
merge_PA_fecha = df_prestamos.merge(df_afluencia, on= "fecha", how = "left")
merge_PA_idafluencia

,id_prestamo,fecha_x,hora_x,id_biblioteca_x,id_usuario,tipo_material,categoria,modalidad_prestamo,dias_prestamo,id_afluencias,fecha_y,hora_y,id_biblioteca_y,visitantes,capacidad_registrada,fuente_registro
0,P0103,2026-09-14,12,B01,U0159,Revista,Infantil,Sala,17,2026-09-14_12_B01,2026-09-14,12.0,B01,106.0,145.0,Conteo de acceso
1,P0186,2026-09-06,9,B01,U0115,Revista,Tecnología,Domicilio,2,2026-09-06_9_B01,2026-09-06,9.0,B01,31.0,145.0,Conteo de acceso
2,P0194,2026-09-08,15,B07,U0021,Libro,Ciencias,Domicilio,15,2026-09-08_15_B07,2026-09-08,15.0,B07,92.0,125.0,Conteo de acceso
3,P0224,2026-09-07,15,B12,U0036,Revista,Literatura,Domicilio,12,2026-09-07_15_B12,NaN,NaN,NaN,NaN,NaN,NaN
4,P0074,2026-09-04,12,B05,U0058,Revista,Arte,Sala,19,2026-09-04_12_B05,2026-09-04,12.0,B05,77.0,130.0,Conteo de acceso
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,P0145,2026-09-02,12,B11,U0147,Libro,Infantil,Domicilio,19,2026-09-02_12_B11,2026-09-02,12.0,B11,125.0,190.0,Conteo de acceso
236,P0073,2026-09-03,18,B11,U0150,Libro,Literatura,Sala,20,2026-09-03_18_B11,2026-09-03,18.0,B11,119.0,190.0,Conteo de acceso
237,P0002,2026-09-07,15,B07,U0016,Libro,Literatura,Sala,18,2026-09-07_15_B07,2026-09-07,15.0,B07,120.0,125.0,Conteo de acceso
238,P0094,2026-09-04,15,B09,U0109,Libro,Infantil,Domicilio,13,2026-09-04_15_B09,2026-09-04,15.0,B09,147.0,170.0,Conteo de acceso
239,P0125,2026-09-06,12,B12,U0004,Revista,Arte,Domicilio,19,2026-09-06_12_B12,2026-09-06,12.0,B12,58.0,120.0,Conteo de acceso

In [66]:
merge_PA_fecha

,id_prestamo,fecha,hora_x,id_biblioteca_x,id_usuario,tipo_material,categoria,modalidad_prestamo,dias_prestamo,id_afluencias_x,hora_y,id_biblioteca_y,visitantes,capacidad_registrada,fuente_registro,id_afluencias_y
0,P0103,2026-09-14,12,B01,U0159,Revista,Infantil,Sala,17,2026-09-14_12_B01,9,B01,49,145,Conteo de acceso,2026-09-14_9_B01
1,P0103,2026-09-14,12,B01,U0159,Revista,Infantil,Sala,17,2026-09-14_12_B01,9,B05,49,130,Conteo de acceso,2026-09-14_9_B05
2,P0103,2026-09-14,12,B01,U0159,Revista,Infantil,Sala,17,2026-09-14_12_B01,9,B06,78,210,Conteo de acceso,2026-09-14_9_B06
3,P0103,2026-09-14,12,B01,U0159,Revista,Infantil,Sala,17,2026-09-14_12_B01,9,B07,28,125,Conteo de acceso,2026-09-14_9_B07
4,P0103,2026-09-14,12,B01,U0159,Revista,Infantil,Sala,17,2026-09-14_12_B01,9,B10,74,150,Conteo de acceso,2026-09-14_9_B10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7528,P0125,2026-09-06,12,B12,U0004,Revista,Arte,Domicilio,19,2026-09-06_12_B12,18,B06,93,210,Conteo de acceso,2026-09-06_18_B06
7529,P0125,2026-09-06,12,B12,U0004,Revista,Arte,Domicilio,19,2026-09-06_12_B12,18,B08,64,140,Conteo de acceso,2026-09-06_18_B08
7530,P0125,2026-09-06,12,B12,U0004,Revista,Arte,Domicilio,19,2026-09-06_12_B12,18,B09,105,170,Conteo de acceso,2026-09-06_18_B09
7531,P0125,2026-09-06,12,B12,U0004,Revista,Arte,Domicilio,19,2026-09-06_12_B12,18,B10,84,150,Conteo de acceso,2026-09-06_18_B10
7532,P0125,2026-09-06,12,B12,U0004,Revista,Arte,Domicilio,19,2026-09-06_12_B12,18,B11,116,190,Conteo de acceso,2026-09-06_18_B11